### ISSUE TITLE
Enable design time support

### ISSUE THREAD

**Issue by ErikEJ** [StevenRasmussen/EFCore.SqlServer.NodaTime#16]
So this can be used in Scaffolding and with EF Core Power Tools.

Requires implementation of design time services/extensions, like the Npgsql extension:

https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG.NodaTime/Scaffolding/Internal/NpgsqlNodaTimeCodeGeneratorPlugin.cs

https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG.NodaTime/Design/Internal/NpgsqlNodaTimeDesignTimeServices.cs

https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG.NodaTime/build/netstandard2.0/Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime.targets

**Comment by StevenRasmussen** [comment]
@ErikEJ - I've created a PR that attempts to add support.  I say "attempts" because TBH, I haven't really used your EF Core Power Tools and so I'm not sure if the PR actually works as it's not clear to me how to test it. I also don't completely understand what is going on in the `.targets` file and so I merely tried to update the parts of that file that were Npgsl specific to be relevant to this project. Any help in testing/validating the PR would be great.

**Comment by ErikEJ** [comment]
Yes, I will test the PR!

**Comment by ErikEJ** [comment]
The design time support actually also works with the command line tools!
