### ISSUE TITLE
Support for EFCore 7

### ISSUE THREAD

**Issue by destacey** [StevenRasmussen/EFCore.SqlServer.NodaTime#31]
Do you plan to support EFCore 7 soon?

I'm spinning up a new project using RC1 and I get the following error when running the initial migration.

```
System.MissingMethodException: Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.
   at SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime.Storage.DateTimeTypeMapping.CreateRelationalTypeMappingParameters(String storeType, Type clrType, ValueConverter valueConverter)
```

When I roll back to EFCore 6 it works perfectly.

Thank you for all the work on this library.

**Comment by StevenRasmussen** [comment]
@destacey - Thanks for the reminder. I was waiting for a RC to update the package. I have created a new branch [here](https://github.com/StevenRasmussen/EFCore.SqlServer.NodaTime/tree/net-7-upgrade). For some reason I'm not able to produce a NuGet package when building the project or if I try to use `dotnet pack`. Is there any chance you could download the branch and see if it produces a NuGet package for you when you build the project?  I'm trying to figure out if the issue is with my machine or something in the .Net 7 bits or the preview of VS.

**Comment by destacey** [comment]
I'm not able to produce the package either.   Everything builds successfully, but no package after the build or if I manually use dotnet pack.

**Comment by ErikEJ** [comment]
@StevenRasmussen you should target .net 6!

**Comment by StevenRasmussen** [comment]
@ErikEJ - Good catch! I have updated to target .Net 6 and I also figured out the issue with the NuGet package not being created. I have uploaded the pre-release version to NuGet.

**Comment by ErikEJ** [comment]
Great news. Will add the package to EF Core Power Tools soon.

**Comment by destacey** [comment]
@StevenRasmussen, thank you.
