### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by djonphillips** [StevenRasmussen/EFCore.SqlServer.NodaTime#5]
I am trying to use your Nuget package to convert a NodaTime Instant to DateTimeOffset in SQL. However, the migration seems to be converting to a DateTime2 type. I am using the latest version of EF Core. Please could you suggest how to change the mapping if this is possible? So far I am manually creating a ValueConverter in the DbContext to achieve this i.e.

var instantToDateTimeOffsetConverter = new ValueConverter<Instant, DateTimeOffset>(v =>
                v.ToDateTimeOffset(),
                v => Instant.FromDateTimeOffset(v));

builder.Entity<User>().Property(p => p.DecisionInstant).HasConversion(instantToDateTimeOffsetConverter).IsRequired(false);

**Comment by StevenRasmussen** [comment]
This is technically possible (with some caveats) but I'm curious why you might want to store it as a `DateTimeOffset` instead of a `DateTime2` since the concept of an `Instant` implies that there is no offset or timezone.  I guess if you were working with a legacy database which happened to store the data in a `DateTimeOffset` column then that could perhaps be the only reason to do so but all of the data would need to be stored with the same offset.

Is there any reason why you would not just use an `OffsetDateTime` NodaTime type instead (which maps to a `DateTimeOffset` in SQL)?

**Comment by djonphillips** [comment]
Thank you. I have reverted back to using Instant and DateTime2 which I can achieve using your package
